library(tidyverse)
library(caret)
library(rpart)
library(dplyr)
setwd("D:/tugasbesar")
getwd()
dataset <- read.csv("dataR2.csv", sep = ",")
dataR2 <- na.omit(dataset)
str(dataR2)
sample_n(dataR2, 10)
set.seed(123)
training.samples <- dataR2$Classification%>%createDataPartition(p = 0.8, list = FALSE)
train.data <- dataR2[training.samples, ]
test.data <- dataR2[-training.samples, ]
set.seed(123)
model <- rpart(Classification~.,data = train.data,method = "class")
par(xpd = NA)
plot(model)
text(model, digits=2)
predicted.classes <- model%>%predict(test.data,type="class")
head(predicted.classes)
head(test.data$Classification)
mean(predicted.classes==test.data$Classification)